// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuTRHq05JtgnAhF-aeTukmlWEL3JBIk6g',
    appId: '1:128135026272:web:dfa86072268dd82e701505',
    messagingSenderId: '128135026272',
    projectId: 'ecomapp-83091',
    authDomain: 'ecomapp-83091.firebaseapp.com',
    storageBucket: 'ecomapp-83091.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB81dv1S14Ica-grNV-D39OJ05s9IxKDpY',
    appId: '1:128135026272:android:df3673819d78a681701505',
    messagingSenderId: '128135026272',
    projectId: 'ecomapp-83091',
    storageBucket: 'ecomapp-83091.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3zcV31ZJd0MOgG9-pRQjWvD6cSRe5YFc',
    appId: '1:128135026272:ios:d423ad8374269173701505',
    messagingSenderId: '128135026272',
    projectId: 'ecomapp-83091',
    storageBucket: 'ecomapp-83091.appspot.com',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3zcV31ZJd0MOgG9-pRQjWvD6cSRe5YFc',
    appId: '1:128135026272:ios:d423ad8374269173701505',
    messagingSenderId: '128135026272',
    projectId: 'ecomapp-83091',
    storageBucket: 'ecomapp-83091.appspot.com',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuTRHq05JtgnAhF-aeTukmlWEL3JBIk6g',
    appId: '1:128135026272:web:d10cda13501d6309701505',
    messagingSenderId: '128135026272',
    projectId: 'ecomapp-83091',
    authDomain: 'ecomapp-83091.firebaseapp.com',
    storageBucket: 'ecomapp-83091.appspot.com',
  );
}
